name: Build TOR SITE only
on:
  pull_request:
    branches: source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout current GITHUB_SHA 
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
      - run: npm install
        name: Run NPM install
      - run: npm run build
        name: Run NPM build
      - run: git config --global user.email "lncm@users.noreply.github.com" && git config --global user.name "LNCM Contributors"
        name: Set up git
      - name: RUn LS
        run: ls       
      - name: Remove node_modules
        run: rm -fr node_modules        
      - name: Change Directory to PUBLIC
        run: cd public/
      - name: Do a LS in PUBLIC
        run: ls
      - name: Push contents of MASTER to nolim1t TOR site
        uses: nolim1t/actions/torscp@0.2.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DEST: ${{ secrets.DEST }}
          SRC: ${{ secrets.SRC }}
