name: Build lncm site with actions
on:
  push:
    branches:
      - source


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout master from this repo
      - name: Checkout submodules associated with this repo
        uses: textbook/git-checkout-submodule-action@1.0.0
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
      - run: npm install
        name: Run NPM install
      - run: npm run build
        name: Run NPM build
      - run: git config --global user.email "lncm@users.noreply.github.com" && git config --global user.name "LNCM Contributors"
        name: Set up git
      - name: Fetch master branch so we can copy it across
        run: git fetch origin master
      - name: Change Origin to SSH
        run: git remote set-url origin git@github.com:lncm/lncm.github.io.git
      - name: Set up SSH environment
        run: mkdir -p ~/.ssh && echo "${PRIVATE_KEY}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - run: npm run deploy
        name: Run Deployment script to MASTER
      - name: Checkout master
        run: git checkout master
      - name: Fetch latest sources
        run: git pull origin master
      - name: Push contents of MASTER to nolim1t TOR site
        uses: nolim1t/actions/torscp@0.2.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DEST: ${{ secrets.DEST }}
          SRC: "*"
